import type { Config } from 'tailwindcss'
import forms from '@tailwindcss/forms'

/**
 * Canonical theme — lifted verbatim from the approved mockups under the design folder.
 * Per design.md Decision 7, this config is the single source of truth for tokens;
 * where it conflicts with the prose in design/calm_fintech_system/DESIGN.md, this wins.
 */
export default <Partial<Config>>{
  darkMode: 'class',
  content: [
    './app/components/**/*.{vue,js,ts}',
    './app/layouts/**/*.vue',
    './app/pages/**/*.vue',
    './app/composables/**/*.{js,ts}',
    './app/plugins/**/*.{js,ts}',
    './app/app.vue',
    './app/error.vue',
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#cbdbf5',
        'on-secondary-container': '#00714d',
        'on-secondary-fixed': '#002113',
        'secondary-fixed-dim': '#4edea3',
        'secondary-fixed': '#6ffbbe',
        outline: '#777587',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#930013',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'on-surface': '#0b1c30',
        'tertiary-fixed-dim': '#ffb3ad',
        'on-error': '#ffffff',
        'on-primary-container': '#dad7ff',
        'on-surface-variant': '#464555',
        'on-background': '#0b1c30',
        'error-container': '#ffdad6',
        'surface-variant': '#d3e4fe',
        surface: '#f8f9ff',
        primary: '#3525cd',
        'inverse-primary': '#c3c0ff',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary-container': '#ffd0cc',
        'primary-fixed': '#e2dfff',
        'secondary-container': '#6cf8bb',
        secondary: '#006c49',
        'tertiary-fixed': '#ffdad7',
        'on-primary': '#ffffff',
        'inverse-surface': '#213145',
        'primary-fixed-dim': '#c3c0ff',
        'tertiary-container': '#bc1d25',
        tertiary: '#960014',
        'primary-container': '#4f46e5',
        'surface-container': '#e5eeff',
        'on-primary-fixed': '#0f0069',
        'surface-tint': '#4d44e3',
        'on-primary-fixed-variant': '#3323cc',
        background: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'on-tertiary-fixed': '#410004',
        'outline-variant': '#c7c4d8',
        'surface-bright': '#f8f9ff',
        'surface-container-high': '#dce9ff',
        'inverse-on-surface': '#eaf1ff',
        'on-error-container': '#93000a',
        'surface-container-highest': '#d3e4fe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '24px',
        base: '8px',
        'container-padding-desktop': '48px',
        'container-padding-mobile': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        gutter: '16px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-lg': ['Inter'],
        'display-currency': ['Inter'],
        'label-caps': ['Inter'],
        'body-sm': ['Inter'],
        'display-currency-mobile': ['Inter'],
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-currency': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-currency-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        // mobile alias used by the mockups (e.g. text-headline-md-mobile)
        'headline-md-mobile': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', fontWeight: '600' }],
      },
      boxShadow: {
        card: '0px 4px 20px rgba(0, 0, 0, 0.04)',
        modal: '0px 10px 32px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [forms],
}
